services:
  _defaults:
    public: false
    autoconfigure: true

  InspiredMinds\ContaoNewsCategoriesSearchBundle\EventListener\ParseTemplate\ModuleSearchListener:
    public: true

  InspiredMinds\ContaoNewsCategoriesSearchBundle\EventListener\ParseTemplate\SearchListener:
    public: true
    arguments: ['@database_connection']

  InspiredMinds\ContaoNewsCategoriesSearchBundle\EventListener\IndexNewsCategoriesListener:
    public: true
    arguments: ['@contao.framework', '@database_connection']
    tags:
      - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate, priority: -255 }

  InspiredMinds\ContaoNewsCategoriesSearchBundle\EventListener\CustomizeSearchListener:
    public: true 
    arguments: ['%kernel.cache_dir%']
