services:
    _defaults:
        autoconfigure: true
        autowire: true

    InspiredMinds\ContaoNewsCategoriesSearchBundle\:
        resource: ../src
        exclude: ../src/{ContaoManager,DependencyInjection,Event,ContaoNewsCategoriesSearchBundle.php}

    InspiredMinds\ContaoNewsCategoriesSearchBundle\EventListener\IndexNewsCategoriesListener:
        tags: [kernel.event_listener]
