services:
    _defaults:
        autoconfigure: true
        autowire: true

    InspiredMinds\ContaoNewsCategoriesSearchBundle\:
        resource: ../src
        exclude: ../src/{ContaoManager,DependencyInjection,Event,ContaoNewsCategoriesSearchBundle.php}

    InspiredMinds\ContaoNewsCategoriesSearchBundle\EventListener\IndexNewsCategoriesListener:
        tags: 
            - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate }

    InspiredMinds\ContaoNewsCategoriesSearchBundle\EventListener\SearchResultListener:
        tags:
            - { name: kernel.event_listener, event: InspiredMinds\ContaoNewsCategoriesSearchBundle\Event\SearchResultEvent, method: __invoke }
